schema = 3

[mod]
  [mod."github.com/antlr/antlr4/runtime/Go/antlr/v4"]
    version = "v4.0.0-20230512164433-5d1fd1a340c9"
    hash = "sha256-kuqZ7vX7JsfGd+VxOK6lb0iVpq62XjKVguTkiPS8QvE="
  [mod."github.com/golang-jwt/jwt"]
    version = "v3.2.2+incompatible"
    hash = "sha256-LOkpuXhWrFayvVf1GOaOmZI5YKEsgqVSb22aF8LnCEM="
  [mod."github.com/klauspost/compress"]
    version = "v1.15.15"
    hash = "sha256-fMVJFz/P37vjZAf82nHjaItaB3gesOa+xV7uBuo3kmg="
  [mod."github.com/labstack/echo/v4"]
    version = "v4.11.1"
    hash = "sha256-uh9C25LiHvevbedA4pU9wgsZpHmjj+KohzNjS8gV2ls="
  [mod."github.com/labstack/gommon"]
    version = "v0.4.0"
    hash = "sha256-xISAIJEu2xh0hoWsORbgjnz3rDK3ft3hrvmxt0wfHVw="
  [mod."github.com/libsql/libsql-client-go"]
    version = "v0.0.0-20230917132930-48c310b27e7b"
    hash = "sha256-6e8+7rco6g11YiHBT45iXj8/NNeQRM1BBQM5TJrwnvE="
  [mod."github.com/libsql/sqlite-antlr4-parser"]
    version = "v0.0.0-20230802215326-5cb5bb604475"
    hash = "sha256-AZ+totf7uhV8A/DLW/gnaFfaWKIApbqwAh7qTMrA3Tc="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.19"
    hash = "sha256-wYQqGxeqV3Elkmn26Md8mKZ/viw598R4Ych3vtt72YE="
  [mod."github.com/valyala/bytebufferpool"]
    version = "v1.0.0"
    hash = "sha256-I9FPZ3kCNRB+o0dpMwBnwZ35Fj9+ThvITn8a3Jr8mAY="
  [mod."github.com/valyala/fasttemplate"]
    version = "v1.2.2"
    hash = "sha256-gp+lNXE8zjO+qJDM/YbS6V43HFsYP6PKn4ux1qa5lZ0="
  [mod."golang.org/x/crypto"]
    version = "v0.11.0"
    hash = "sha256-aFI8cpvSZRiQO2HQm6+a4e9OiSf7GUfj69SSta2iZ44="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20220722155223-a9213eeb770e"
    hash = "sha256-kNgzydWRpjm0sZl4uXEs3LX5L0xjJtJRAFf/CTlYUN4="
  [mod."golang.org/x/net"]
    version = "v0.12.0"
    hash = "sha256-zQZBj42+wLLxXwS/e+KNbu8+SukMDxxW23WSi5XQXAA="
  [mod."golang.org/x/sys"]
    version = "v0.10.0"
    hash = "sha256-eeifyHj8IcTAruekJAGMCcjFyU2GAIAgvxS36hPZM1U="
  [mod."golang.org/x/text"]
    version = "v0.11.0"
    hash = "sha256-W/XvTPAGIOlFVwZ7rTaEid7pdRtb4wc6a+nyOW99/ks="
  [mod."golang.org/x/time"]
    version = "v0.3.0"
    hash = "sha256-/hmc9skIswMYbivxNS7R8A6vCTUF9k2/7tr/ACkcEaM="
  [mod."nhooyr.io/websocket"]
    version = "v1.8.7"
    hash = "sha256-6pQ35gFvbyMhNo0gv4bPxYDUrwDF/ok1GMA+BHfsRRM="
